Repository wordpress-mobile/WordPressUI-iOS, pull requests merged in 2021-06, with the labels that each got.

#94 Addresses a difference between BottomSheetVC's way of handle dismissals across device types.
  WordPressUI.podspec
  WordPressUI/BottomSheet/BottomSheetViewController.swift
Labels: bug

#95 Allow bottom sheet children to override supportedInterfaceOrientation
  WordPressUI.podspec
  WordPressUI/BottomSheet/BottomSheetViewController.swift
Labels: enhancement

#96 BottomSheetViewController: allow forcing formSheet modal presentation on iPad
  WordPressUI/BottomSheet/BottomSheetViewController.swift
Labels: enhancement

#98 Merge 1.12.1 into trunk
  Gemfile.lock
  WordPressUI.podspec
  WordPressUI/BottomSheet/BottomSheetViewController.swift
Labels: Releases
