Repository wordpress-mobile/WordPressUI-iOS, pull requests merged in 2024-02, with the labels that each got.

#141 Update version to `1.15.1`
  CHANGELOG.md
  WordPressUI.podspec
Labels: Releases

#145 Add Dangermattic configuration
  .github/workflows/run-danger.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: tooling

#147 Setup SwiftLint in the project and on CI
  .buildkite/pipeline.yml
  .swiftlint.yml
  Example/Example/AppDelegate.swift
  Example/Example/KeyboardAnimationsExampleViewController.swift
  Example/Example/ViewController.swift
  Package.resolved
  Package.swift
  Sources/WordPressUI/BottomSheet/BottomSheetAnimationController.swift
  Sources/WordPressUI/BottomSheet/DrawerPresentationController.swift
  Sources/WordPressUI/Constants/UIKitConstants.swift
  Sources/WordPressUI/Extensions/BlockEvents/UIBarButtonItem+BlockEvents.swift
  Sources/WordPressUI/Extensions/CGAffineTransform+Helpers.swift
  Sources/WordPressUI/Extensions/UIImage+Assets.swift
  Sources/WordPressUI/Extensions/UIImage+Crop.swift
  Sources/WordPressUI/Extensions/UIImageView+Blavatar.swift
  Sources/WordPressUI/Extensions/UIImageView+Gravatar.swift
  Sources/WordPressUI/Extensions/UIImageView+Networking.swift
  Sources/WordPressUI/Extensions/UITableView+Helpers.swift
  Sources/WordPressUI/Extensions/UITableViewController+Helpers.swift
  Sources/WordPressUI/Extensions/UITextField+TextHelper.swift
  Sources/WordPressUI/Extensions/UIView+Animations.swift
  Sources/WordPressUI/Extensions/UIView+Helpers.swift
  Sources/WordPressUI/Extensions/UIViewController+ChildViewController.swift
  Sources/WordPressUI/FancyAlert/FancyAlertView.swift
  Sources/WordPressUI/FancyAlert/FancyAlertViewController.swift
  Sources/WordPressUI/FancyAlert/FancyButton.swift
  Sources/WordPressUI/FlingableView/FlingableViewHandler.swift
  Sources/WordPressUI/Ghosts/GhostOptions.swift
  Sources/WordPressUI/Ghosts/GhostStyle.swift
  Sources/WordPressUI/Ghosts/Internal/GhostAnimation.swift
  Sources/WordPressUI/Ghosts/Internal/GhostCollectionViewHandler.swift
  Sources/WordPressUI/Ghosts/Internal/GhostLayer.swift
  Sources/WordPressUI/Ghosts/Internal/GhostTableViewHandler.swift
  Sources/WordPressUI/Ghosts/Internal/UIView+InnerGhost.swift
  Sources/WordPressUI/Ghosts/UICollectionView+Ghost.swift
  Sources/WordPressUI/Ghosts/UITableView+Ghost.swift
  Sources/WordPressUI/Ghosts/UIView+Ghost.swift
  Tests/WordPressUITests/Extensions/UIViewControllerHelperTest.swift
  Tests/WordPressUITests/Ghosts/UITableView+GhostTests.swift
  fastlane/Fastfile
Labels: tooling

#146 Use Gravatar.ImageCaching protocol instead of defining our own
  Sources/WordPressUI/Extensions/UIImageView+Networking.swift
Labels: Gravatar
